services:
  - type: web
    name: my-service
    env: production
    region: us-west
    build_command: npm run build
    runtime: node
    port: https://company-xbla.onrender.com
    routes:
      - type: rewrite
        path: /about
        redirect: /
      - type: rewrite
        path: /services
        redirect: /
      - type: static
        path: /static/
        destination: public/
